openapi: "3.0.0"
info:
  version: 1.0.0
  title: College Sever API
  license:
    name: MIT
servers:
  - url: http://locahost:8080
paths:
  /ping:
    get:
      summary: server test api
      operationId: ping
      tags:
        - ping
      responses:
        '200':
          description: 'College Server is running'

  /api/v1/auth/signup:
    post:
      summary: 'signup api for Admin'
      operationId: 'sign-up'
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: User Sign Up is success
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/auth/signin:
    post:
      summary: 'sign in api for Admin'
      operationId: 'sign-in'
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: User Sign Up is success
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/college/ping:
    get:
      summary: 'test api for sign in verification'
      operationId: 'sign-in-ping'
      tags:
        - ping
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'user is authorised'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserJwtResponse'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/auth/resetPassword:
    post:
      summary: 'api for password change'
      operationId: 'reset-password'
      tags:
        - auth
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserResetPassword'
      responses:
        200:
          description: 'Password change success'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/college/get:
    get:
      summary: 'get all details permitted based on logged in user'
      operationId: 'get-info'
      tags:
        - college
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'Details fetched successfully'
          content:
            application/json:
              schema:
                type: object
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/college/registerCourses:
    post:
      summary: 'api for students to register for courses'
      operationId: 'register-courses'
      tags:
        - auth
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Courses'
      responses:
        200:
          description: 'Course registration success'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/college/updateUser:
    post:
      summary: 'api to update user details'
      operationId: 'update-user'
      tags:
        - college
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        200:
          description: 'update user success'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/college/addUser:
    post:
      summary: 'api to add user details'
      operationId: 'add-user'
      tags:
        - college
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUser'
      responses:
        200:
          description: 'add user success'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'
  /api/v1/college/addCourse:
    post:
      summary: 'api to add course details'
      operationId: 'add-course'
      tags:
        - college
      parameters:
        - in: header
          name: AUTH_TOKEN
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        200:
          description: 'add course success'
        400:
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse500'

components:
  schemas:
    ErrorResponse:
      properties:
        code:
          description: 'Error Code denoting the cause of failure'
          type: integer
        message:
          description: 'Error Message denoting the cause of failure'
          type: string

    ErrorResponse500:
      properties:
        code:
          description: 'Error Code denoting the cause of failure. 500: Internal Processing Error.'
          type: integer
        message:
          description: 'Error Message denoting the cause of failure'
          type: string

    User:
      type: object
      required: [ 'email', 'password' ]
      properties:
        first_name:
          type: string
          maxLength: 30
        last_name:
          type: string
          maxLength: 30
        email:
          type: string
        password:
          type: string
          minLength: 6
    AddUser:
      type: object
      required: ['email', 'password', 'role_id']
      properties:
        email:
          type: string
        password:
          type: string
        role_id:
          type: integer
          minimum: 1
          maximum: 3
        first_name:
          type: string
          maxLength: 30
        last_name:
          type: string
          maxLength: 30
    UpdateUser:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 30
        last_name:
          type: string
          maxLength: 30
    UserJwtResponse:
      type: object
      properties:
        role_id:
          type: integer
        user_id:
          type: string
        access_token:
          type: string
        iss:
          type: string
        sub:
          type: string
    UserResetPassword:
      type: object
      required: [ 'email', 'password' , 'resetPassword' ]
      properties:
        email:
          type: string
        password:
          type: string
          minLength: 6
        resetPassword:
          type: string
          minLength: 6
    Course:
      type: object
      properties:
        title:
          type: string
        credits:
          type: integer
        teacher_id:
          type: string
    Courses:
      type: object
      properties:
        courseIdList:
          type: array
          items:
            type: string